name: Deploy to Master Pages
on:
  push:	
    branches:	
      - source

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@source
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install and build
      run: |
        npm install
        npx @11ty/eleventy

    - name: Deploy
      uses: s0/git-publish-subdir-action@source
      env:
        REPO: self
        BRANCH: master
        FOLDER: _site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
